// Writes THIRD-PARTY-NOTICES.md: the licence of every package built into
// UNCLI, so a release carries the notices its dependencies ask for.
//
//   node scripts/notices.mjs [--check]
//
// Go: the modules linked into the Windows production build (go list -deps
// with Wails' desktop,production tags), plus the Go standard library.
// Frontend: the runtime dependencies of app/frontend (npm ls --omit=dev),
// which is a superset of what Vite bundles. Licence texts are read from the
// module cache and node_modules, so run `npm ci` in app/frontend first.
//
// --check exits 1 if the file is out of date, without writing it.

import { execFileSync, execSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const appDir = join(root, 'app')
const frontendDir = join(appDir, 'frontend')
const out = join(root, 'THIRD-PARTY-NOTICES.md')

const licenceFile = /^(licen[cs]e|copying|notice)(\.(md|txt|markdown))?$|^licen[cs]e[-_.]/i

// The licence and notice files at the top of a package folder, NOTICE last.
function licenceTexts(dir) {
  if (!dir || !existsSync(dir)) return []
  return readdirSync(dir)
    .filter(f => licenceFile.test(f))
    .sort((a, b) => /notice/i.test(a) - /notice/i.test(b) || a.localeCompare(b))
    .map(f => readFileSync(join(dir, f), 'utf8').replace(/\r\n/g, '\n').trim())
}

function goModules() {
  const env = { ...process.env, GOOS: 'windows', GOARCH: 'amd64' }
  const lines = execFileSync(
    'go',
    ['list', '-deps', '-tags', 'desktop,production', '-f', '{{with .Module}}{{if not .Main}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}', '.'],
    { cwd: appDir, env, encoding: 'utf8' },
  )
  const seen = new Map()
  for (const line of lines.split(/\r?\n/).filter(Boolean)) {
    const [name, version, dir] = line.split('\t')
    seen.set(name, { name, version, texts: licenceTexts(dir) })
  }
  // No version for the standard library: it would change with whichever Go
  // patch release builds UNCLI, which doesn't change the licence.
  const goroot = execFileSync('go', ['env', 'GOROOT'], { encoding: 'utf8' }).trim()
  return [{ name: 'Go standard library', version: '', texts: licenceTexts(goroot) }, ...[...seen.values()].sort((a, b) => a.name.localeCompare(b.name))]
}

function npmPackages() {
  // npm ls exits 1 on extraneous or invalid packages but still prints the tree.
  let paths
  try {
    paths = execSync('npm ls --omit=dev --all --parseable', { cwd: frontendDir, encoding: 'utf8' })
  } catch (e) {
    paths = e.stdout ?? ''
  }
  const seen = new Map()
  for (const dir of paths.split(/\r?\n/).filter(Boolean)) {
    const pkgFile = join(dir, 'package.json')
    if (!existsSync(pkgFile)) continue
    const pkg = JSON.parse(readFileSync(pkgFile, 'utf8'))
    if (dir.replace(/[\\/]$/, '') === frontendDir.replace(/[\\/]$/, '')) continue
    const key = `${pkg.name}@${pkg.version}`
    if (seen.has(key)) continue
    const licence = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? (pkg.licenses ?? []).map(l => l.type).join(' OR ')
    seen.set(key, { name: pkg.name, version: pkg.version, licence, texts: licenceTexts(dir) })
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))
}

function section(p) {
  const head = `### ${[p.name, p.version].filter(Boolean).join(' ')}${p.licence ? ` (${p.licence})` : ''}`
  const body = p.texts.length
    ? p.texts.map(t => '```text\n' + t.replace(/```/g, "'''") + '\n```').join('\n\n')
    : p.licence
      ? `Licensed under ${p.licence}; the package ships no licence text.`
      : 'The package ships no licence text.'
  return `${head}\n\n${body}`
}

const goList = goModules()
const npmList = npmPackages()

const text = `# Third-party notices

UNCLI is MIT licensed (see \`LICENSE\`). It is built with the open-source
software listed below, each under its own licence, reproduced here as the
package ships it. This file is generated by \`npm run notices\`; don't edit it
by hand.

UNCLI doesn't include any AI provider's CLI. It downloads a pinned copy from
the provider when you install one in Settings → AI Providers, and each CLI is
used under its provider's own terms. A container's Linux image (Alpine) is
likewise downloaded when you build the container, under Alpine's licences.

## Go modules (${goList.length})

${goList.map(section).join('\n\n')}

## Frontend packages (${npmList.length})

${npmList.map(section).join('\n\n')}
`

if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : ''
  if (current !== text) {
    // Say where it differs, so a check that fails only in CI can be read.
    const want = text.split('\n')
    const have = current.split('\n')
    const i = want.findIndex((l, k) => l !== have[k])
    const at = i < 0 ? want.length : i
    console.error(`THIRD-PARTY-NOTICES.md is out of date: run npm run notices. First difference at line ${at + 1}:`)
    console.error(`  file:      ${JSON.stringify(have[at] ?? '(end of file)')}`)
    console.error(`  generated: ${JSON.stringify(want[at] ?? '(end of file)')}`)
    process.exit(1)
  }
  console.log('THIRD-PARTY-NOTICES.md is up to date.')
} else {
  writeFileSync(out, text)
  const missing = [...goList, ...npmList].filter(p => !p.texts.length).map(p => `${p.name} ${p.version}`)
  console.log(`Wrote THIRD-PARTY-NOTICES.md: ${goList.length} Go modules, ${npmList.length} frontend packages.`)
  if (missing.length) console.log(`No licence text shipped by: ${missing.join(', ')}`)
}
